---
title: "Sentiment Analysis with R"
author: "Somnath Mukherjee"
date: "June 12, 2019"
output: html_document
---

## R Markdown

Install and Load Required Packages  

```{r,warning=FALSE,message=FALSE}
ipak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) 
        install.packages(new.pkg, dependencies = TRUE)
    sapply(pkg, require, character.only = TRUE)
}

# usage
packages <- c("knitr", "kableExtra", "tidyverse","psych", "PerformanceAnalytics",
              "GGally", "gridExtra", "corrplot","SentimentAnalysis","tm")
ipak(packages)

```



```{r}
# Simple example using a sentence. Note use of function 
# convertToBinaryResponse() to convert a vector of
# continuous sentiment scores into a factor object.
sentiment <- analyzeSentiment("My visit to Starbucks today was really lousy.")
convertToBinaryResponse(sentiment)$SentimentQDAP

```

```{r}
 # More extensive example using the acq data sent from tm
 # package, a corpus of 50 Reuters news articles dealing 
 # with corporate acquisitions.
 data(acq)
```


```{r}
 # Analyze sentiment, pass corpus
 # The names of the columns are: "WordCount", "SentimentGI",
 # "NegativityGI", "PositivityGI", "SentimentHE",
 # "NegativityHE", "PositivityHE", "SentimentLM",
 # "NegativityLM", "PositivityLM", "RatioUncertaintyLM",
 # "SentimentQDAP", "NegativityQDAP", "PositivityQDAP"
 #  Produces data frame 50x14
 sentiment <- analyzeSentiment(acq) 

```

```{r}
 # Numeric vector containing sentiment statistics for each
 # article
 class(sentiment$NegativityLM)
 # Count positive and negative categories for the 
 # 50 news releases. 
 table(convertToBinaryResponse(sentiment$SentimentLM))
 # News releases with highest and lowest sentiment
 # Show highest 
 acq[[which.max(sentiment$SentimentLM)]]$meta$heading
 # Show lowest 
 acq[[which.min(sentiment$SentimentLM)]]$meta$heading
```

```{r}
 # View summary statistics of sentiment variable
  summary(sentiment$SentimentLM)
```

```{r}
 # Visualize density of standardized sentiment variable values
 hist(sentiment$SentimentLM, probability=TRUE,
     main="Histogram: Density of Distribution for Standardized Sentiment Variable")
 lines(density(sentiment$SentimentLM))
```

```{r}
 # Draw a simple line plot to visualize the evolvement of 
 # sentiment scores. Helpful when studying a time series 
 # of sentiment scores.
 plotSentiment(sentiment$SentimentLM, xlab="Reuters News Articles")
```

